.github/pull_request_template.md

close: #16 
> 템플릿 수정(pr 작성시 메인 레포지토리(kernal360)에 현재 레포지토리의 이슈번호 동기화)
- 본 레포지토리 이슈번호와 연동되도록 템플릿 수정

fix: pull request 템플릿 수정

---

package.json
pnpm-lock.yaml
src/components/shared/animation/ListLoading.tsx
src/page/profile/MyPage.tsx
src/page/profile/components/ExperiencePoint.tsx
src/page/profile/components/ProfileImage.tsx

> editor 의존성 추가 및 불필요한 import 제거
- TOAST UI Editor 의존성 추가
- 이전 코드에서 불필요한 import 제거

chore: editor 의존성 추가 및 불필요한 import 제거

---

src/mocks/handler/answer.ts
src/page/qna-detail/components/Markdown/MdEditor.tsx
src/page/qna-detail/components/MyAnswer.tsx

close: [#32](https://github.com/KernelSquare/Frontend/issues/32)
> 답변 생성 시 msw handler에서 추가 데이터가 반영되지 않는 오류를 해결하였습니다.
- msw handler에서 참조하는 데이터를 수정하여 답변 생성 관련 오류를 해결하였습니다.

fix: 답변 생성 관련 msw 에러 해결

---

components.json
package.json
pnpm-lock.yaml
src/app/globals.css
src/components/ui/button.tsx
src/lib/utils.ts
tailwind.config.ts

close: [#61 ](https://github.com/KernelSquare/Frontend/issues/61)
> UI 구현 시 효율적인 개발을 위해 shadcn/ui를 설치 후 공용 버튼을 구현하였습니다.
- shadcn/ui 설치 후 tailwind.config 등 충돌되는 부분을 수정하여 적용을 완료하였습니다.
- 기존에 shared에 구현 되어 있던 공용 버튼을 shadcn/ui의 버튼으로 대체할 수 있도록 ui/button.tsx를 수정하였습니다.

Design: Shadcn/ui 적용

---

src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
src/page/coffee-chat/detail/EnterCoffeeChat.tsx
src/socket/client/MessageControl.tsx
src/util/validate.ts

close: [#91](https://github.com/KernelSquare/Frontend/issues/91)
> 버그 수정, api 연동
- 채팅 메시지 입력후 엔터시 일부글자 중복체출되는 현상 수정
- 채팅 입장 api를 활용하는 것으로 로직 수정
- 이메일 입력시 한글이 포함되어있을 경우 유효하지 않도록 설정

fix: 버그 fix

---

src/components/layout/header/search/SearchArea.tsx
src/components/layout/header/search/SearchModal.tsx
src/components/shared/toast-ui-editor/editor/Editor.tsx
src/constants/message.ts
src/mocks/db/answers.ts
src/mocks/db/user.ts
src/mocks/handler/answer.ts
src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
src/page/coffee-chat/create/components/CustomCalendar/CustomCalendar.tsx
src/page/coffee-chat/create/components/ScheduleSection.tsx
src/page/coffee-chat/create/hooks/useGetScheduleList.tsx
src/page/qna-detail/QnADetail.tsx
src/page/qna-detail/components/Answers/VoteBox.tsx
src/page/qna-detail/components/MyAnswer.tsx
src/page/qna-detail/hooks/useAnswerVote.tsx
src/page/qna-detail/hooks/useHandleMyAnswer.tsx
src/page/qna-detail/hooks/useQnADetail.tsx
src/page/user-profile/components/introduction/Introduction.tsx
src/react-query/answers.ts
src/recoil/atoms/mode.tsx

close: [#90 ](https://github.com/KernelSquare/Frontend/issues/90)
> 투표 등 진행 요청 시 `isPending` 또는 `status` 사용하여 처리
> 특정 일자에서만 멘토링 가능 일자가 4일로 보이는 현상 처리
> 다른 날짜 선택 시 기존에 있던 atomFamily 초기화
> 동일한 날짜 두 번 클릭 시 초기화 되던 기능 삭제하고 초기화 버튼 별도로 생성하기
> 투표 삭제 시 모달 -> toast로 수정
> 답변 생성 창 다시 노출되는 오류 수정
> 자기소개 null 값 제출 허용되도록 수정
close: [#96  ](https://github.com/KernelSquare/Frontend/issues/96)
> 큰 화면, 작은 화면 검색 결과 다른 현상 해결
close: [#97 ](https://github.com/KernelSquare/Frontend/issues/97)
> 신규 생성 아이디들 마이페이지 Readme.md 버튼 활성화가 안 되는 문제 해결
close: [#98 ](https://github.com/KernelSquare/Frontend/issues/98)
> 본인 답변에서 수정 불가하도록 수정
close: [#99  ](https://github.com/KernelSquare/Frontend/issues/99)
> `myanswer` 관련 전역 상태 의존성 수정하여 본인 질문글에서 답변 제출 에디터 뜨는 문제 해결

fix: QA 오류 사항 수정

---

src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
src/page/coffee-chat/detail/EnterCoffeeChat.tsx
src/page/coffee-chat/detail/reservation/ScheduleMentoringSession.tsx
src/page/coffee-chat/detail/reservation/mentor/ReservationForMentor.tsx

> 커피챗 입장하기 버튼 비활성화 관련 로직 추가
- 멘토의 경우 해당 예약 정보 옆에 커피챗 입장하기 버튼이 생기도록 수정하였습니다.
- 시간이 되지 않거나 지난 커피챗의 경우 입장하기 버튼이 비활성화 되도록 처리하였습니다.

fix: 커피챗 입장하기 버튼 비활성화 관련 로직 추가

---

src/components/shared/tag/HashTag.tsx
src/components/shared/tag/Tag.tsx
src/page/coffee-chat/main/CoffeeChatList.tsx
src/page/qna/components/QnAList.tsx

close: [#122](https://github.com/KernelSquare/Frontend/issues/122)
> 1차 고객의 소리 반영 수정
- 커서 스타일 수정
- 카드 전체를 링크 이동 가능한 영역으로 설정

fix: 태그 UI, 카드 UI 수정

---

src/components/shared/input/Guideline.tsx
src/page/signup/Signup.tsx
src/util/validate.ts

close: [#123](https://github.com/KernelSquare/Frontend/issues/123)
> 회원가입 비밀번호 유효성 로직 수정
- 1차 고객의 소리 반영하여 회원가입 비밀번호 유효성 로직 수정

fix: 회원가입 유효성 수정

---

.github/workflows/ci-workflow.yml

[#125 ](https://github.com/KernelSquare/Frontend/issues/125)

fix: workflow 파일 syntax error 해결

---

Dockerfile

close: [#125 ](https://github.com/KernelSquare/Frontend/issues/125)

fix: Dockerfile 버전 오류 해결

---

.github/workflows/ci-workflow.yml

[#125](https://github.com/KernelSquare/Frontend/issues/125)
> ci yml 수정
- \ 제거
- notify job if에 always() 추가

fix: ci yml 수정

---

.github/workflows/cd-workflow.yml

> cd를 위한 github action workflow 생성하였습니다.

feat: cd를 위한 github action workflow 생성

---

.github/workflows/cd-workflow.yml

> appleboy/ssh-action 관련 cd workflow syntax error를 해결하였습니다 .

fix: cd workflow syntax error 해결

---

.github/workflows/cd-workflow.yml

> workflow에 aws credentials Permission 정보를 추가하였습니다.

fix: workflow에 aws credentials Permission 정보 추가

---

.github/workflows/cd-workflow.yml

fix: cd 관련 workflow 파일 수정

---

.github/workflows/cd-workflow.yml

> cd workflow에 aws region 관련 환경 변수 관련 사항을 반영하였습니다.

fix: cd workflow 환경 변수 수정 사항 반영

---

.github/workflows/cd-workflow.yml

> 버전 이슈 해결을 위해 aws-credentials 버전을 수정하였습니다.

fix: aws-credentials 버전 수정

---

.github/workflows/cd-workflow.yml

> cd workflow 파일에 checkout과 관련된 코드를 추가하였습니다.

fix: cd workflow checkout 관련 코드 추가

---

.github/workflows/cd-workflow.yml

> 기존 `PULL_REQUEST` 액션에서 외부 레포지토리에서 포크된 현재 상황에서의 CD를 가능하게 하는 `PULL_REQUEST_TARGET`으로 github action으로 수정하였습니다.

fix: github actions 수정

---

.github/workflows/cd-workflow.yml

> cd workflow에서 레포지토리 관련 조건식을 삭제하였습니다.

chore: cd workflow 조건문 삭제

---

.github/workflows/cd-workflow.yml

> github action workflow에 node.js의 version 설정을 위한 코드를 추가하였습니다.

fix: node version 관련 설정 추가

---

.github/workflows/cd-workflow.yml

> node.js의 version 명시와 관련된 코드를 수정하였습니다.

fix: node version 관련 코드 수정

---

.github/workflows/cd-workflow.yml

> Public IP와 관련된 action을 변경하였습니다.

fix: public IP action 변경

---

.github/workflows/cd-workflow.yml

> Public IP를 위한 github action을 수정하였습니다.

fix: github 동적 IP를 위한 action 수정

---

.github/workflows/cd-workflow.yml

> github actions에서 ec2 인증 방식을 변경하여 이미지 업로드 관련 오류를 해결하였습니다.

fix: github actions ec2 인증 방식 변경

---

.github/workflows/cd-workflow.yml

> slack notification이 항상 실행되도록 설정을 변경하였습니다.

fix: slack notification 관련 설정 변경

---

.github/workflows/cd-workflow.yml
.github/workflows/ci-workflow.yml

> CI/CD가 적절한 레포지토리에서 동작할 수 있도록 제한 조건을 추가하였습니다.

feat: CI/CD workflow 레포 제한 추가

---

.github/workflows/cd-workflow.yml
.github/workflows/ci-workflow.yml

> github repositofy 이름을 명시하여 원하지 않는 skip 현상이 발생하지 않도록 하였습니다.

fix: github repository 이름 명시하도록 수정

---

src/app/chat/_components/ChatError.tsx
src/app/chat/room/[id]/page.tsx
src/interfaces/dto/coffee-chat/enter-chat-room.ts
src/page/coffee-chat/chat/ChatRoom.tsx
src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
src/page/coffee-chat/detail/EnterCoffeeChat.tsx
src/page/coffee-chat/detail/reservation/mentor/ReservationForMentor.tsx
src/service/coffee-chat.ts

close: [#183](https://github.com/KernelSquare/Frontend/issues/183)
> reservation_id 를 적용
- reservation_id를 반영하는 것으로 선반영

hotfix: 채팅 reservation_id

---

src/mocks/handler/coffee-chat.ts

close: [#183](https://github.com/KernelSquare/Frontend/issues/183)
- mock 핸들러 수정

hotfix: 채팅

---

src/app/chat/_components/ChatError.tsx
src/app/chat/room/[id]/page.tsx
src/interfaces/dto/coffee-chat/enter-chat-room.ts
src/mocks/handler/coffee-chat.ts
src/page/coffee-chat/chat/ChatRoom.tsx
src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
src/page/coffee-chat/detail/EnterCoffeeChat.tsx
src/page/coffee-chat/detail/reservation/mentor/ReservationForMentor.tsx
src/service/coffee-chat.ts

chore: hotfix 반영

---

src/constants/select.ts
src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
src/page/coding-meetings/create/components/HashTagsSection.tsx

> 트러블슈팅 시 발생했던 오류를 수정했습니다.
- 모각코 개설/수정 버튼 메시지 변경
- 인원수 최소 값 수정
- hashtag 값이 담기지 않는 오류 해결

fix: QA 수정사항 반영

---

src/page/coding-meetings/detail/Comments.tsx
src/page/coding-meetings/detail/DetailPage.tsx
src/page/coding-meetings/detail/UserInfo.tsx
src/page/faq/FaQPage.tsx

close: [#196](https://github.com/KernelSquare/Frontend/issues/196)
> 수정사항 반영
- 상세 수정사항 반영
- 구글 폼 링크 주소 수정

fix: 상세 수정사항 반영 , 구글 폼 주소 수정

---

src/page/coding-meetings/detail/Comments.tsx
src/page/coding-meetings/detail/DetailPage.tsx

> 댓글 최소, 상세 시간 콘솔
- 댓글 최소10자 적용
- 상세페이지에서의 시간 분석을 위한 콘솔 추가

fix: 댓글 최소, 콘솔 적용

---

src/components/shared/TextCounter.tsx

close: [#215](https://github.com/KernelSquare/Frontend/issues/215)
> 공용 텍스트 길이 카운터 컴포넌트
- 텍스트 길이 카운터 컴포넌트

feat: 공용 텍스트 길이 카운터

---

src/components/form/LoginForm.tsx
src/page/coding-meetings/main/info-area/QnAInfoArea.tsx

- 질문 작성 링크 주소 수정
- 로그인 중일 때 로그인 중 문구 보여주는 것으로 수정

fix: 질문 작성 링크주소 수정

---

src/components/form/LoginForm.tsx
src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
src/page/coding-meetings/main/info-area/QnAInfoArea.tsx

- 질문 작성 링크 주소 수정
- 로그인 중일 때 로그인 중 문구 보여주는 것으로 수정

fix: 질문 작성 링크 주소, 로그인 중 문구

---

src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx

popupLocalStorage가 배열형태가 아닌 경우
false로 초기화

fix: popupStorage

---

src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx
src/util/chat/popup.ts

fix: localStorage 초기화

---

src/page/coffee-chat/detail/EnterCoffeeChat/EnterCoffeeChatButton.tsx
src/util/chat/popup.ts

localStorage 예외 케이스 추가

---

.github/workflows/dev-cd-workflow.yml
.github/workflows/dev-ci-workflow.yml

> 개발서버 CI/CD
- CI / CD 워크플로우 작성

개발서버 CI/CD

---

.github/workflows/dev-ci-workflow.yml

Sentry 환경변수 제거

---

next.config.js
src/page/coding-meetings/detail/kakao-map/KakaoMapError.tsx

fix: sentry

---

.github/workflows/dev-cd-workflow.yml

fix: CD 수정

---

.github/workflows/dev-ci-workflow.yml

fix: CI 수정

---

src/page/oauth/github/OAuthGithubSuccess.tsx
src/page/user-profile/components/UserProfilePresenter.tsx
src/page/user-profile/edit-nickname/form/SubmitStep.tsx

[#286](https://github.com/KernelSquare/Frontend/issues/286)
- 닉네임 수정 이후 유저 상태가 유지되도록 함
- 내 프로필 페이지인 경우에만 설정 버튼 노출

fix: 닉네임 수정

---

src/components/layout/header/alerm/Alerm.tsx
src/hooks/sse/useSSE.tsx

[#236](https://github.com/KernelSquare/Frontend/issues/236)
- 훅이 여러번 호출되어도 같은 eventSource를 참조 할 수 있도록 수정

refactor: useSSE

---

src/app/chat/[id]/page.tsx
src/app/chat/create/page.tsx
src/app/chat/page.tsx
src/app/chat/room/[id]/page.tsx
src/app/chat/u/[id]/page.tsx
src/app/coding-meetings/[token]/page.tsx
src/app/coding-meetings/create/page.tsx
src/app/coding-meetings/page.tsx
src/app/coding-meetings/post/[token]/page.tsx
src/app/faq/page.tsx
src/app/layout.tsx
src/app/notification/page.tsx
src/app/page.tsx
src/app/profile/[id]/page.tsx
src/app/profile/nickname/page.tsx
src/app/qna/page.tsx
src/app/question/[id]/page.tsx
src/app/search/page.tsx
src/app/signup/page.tsx
src/constants/layoutMeta.ts

[#303](https://github.com/KernelSquare/Frontend/issues/303)
> 오픈그래프(og), 트위터카드(twitter)
- 모든 페이지에 오픈 그래프와 트위터 카드를 적용하여 소셜 SEO를 개선하였습니다.

chore: 모든 페이지 og, twitter card 적용

---

src/app/coding-meetings/[token]/page.tsx

- 모각코 상세 meta og url 상대 주소로 수정

모각코 상세 meta og url 상대 주소로 수정

---

src/app/coding-meetings/[token]/page.tsx
src/page/coding-meetings/util/cm-token.ts

- 모각코 상세 meta og url 상대 주소로 수정

[fix] 모각코 상세 meta og url 상대주소로 수정

---

src/app/coding-meetings/[token]/page.tsx
src/page/coding-meetings/util/cm-token.ts

- /coding-meetings/ 이후 소문자로 시작하도록 수정

[fix] 모각코 상세 url 형식 수정

---

README.md

[#311](https://github.com/KernelSquare/Frontend/issues/311)
> 모각코 상세 url 수정
- cm_ 제외, 대문자로 시작할 경우 소문자로 적용되도록 수정

[fix] 모각코 상세 url 형식 수정 (dev)

---

src/page/coding-meetings/util/cm-token.ts

- 카카오톡 소셜 미리보기에서 invalid url 이 적용되지 않는 형식으로 수정해 봄

모각코 상세 url 수정

---

src/page/coding-meetings/detail/DetailPage.tsx

- 500 응답이 발생되지 않는 상황에서 모각코 상세 og 가 잘 적용되는지 보기 위함 (추측이 맞을 경우, 서버 렌더링에서도 에러가 없을 경우 200 응답일 것이며, 해당 상황에서는 정상적으로 og가 반영되어야 함)
- 렌더링은 되지만, 500에러가 콘솔에 확인되는 것이 서버 렌더링시 발생하는 localStorage 관련 에러로 추정되어 dynamic 으로 ssr 되지 않도록 수정

fix: 모각코 댓글 dynamic 적용

---

src/app/coding-meetings/[token]/page.tsx
src/page/coding-meetings/detail/DetailPage.tsx
src/page/coding-meetings/util/cm-token.ts

> 모각코 상세 og
- 서버렌더링에서도 에러가 발생하지 않도록 해서 og가 올바르게 적용될 수 있도록 수정 (이전에 결과적으로 렌더링 정상 및 탭에서 확인되는 제목 등도 정상이었으나, 서버 렌더링에서만 localStorage 관련 에러로 잠시 500 응답 발생)

[fix] 모각코 상세 og

---

src/app/api/send-fcm/route.ts

#361
> 환경변수의 개행문자 수정 및 코드에서 처리방식 변경
- 올바르지 않은 형식이라는 에러가 발생하여 admin 초기화가 실패해서 문자 처리 방식을 변경

fix: pem 개행문자 처리 방식 수정
