KernelSquare/Frontend

src/components/shared/Profile.tsx

close: [#28](https://github.com/KernelSquare/Frontend/issues/28)
> 드롭다운 이슈 수정
- 프로필 이미지가 없을 경우 클릭시 드롭다운이 보여질 수 있도록 수정
- 확장성을 고려하여 props 수정

fix: 헤더 프로필 영역 드롭다운 이슈 수정

---

src/page/qna-detail/components/Markdown/MdEditor.tsx
src/page/qna-detail/components/Markdown/MdViewer.tsx

> fix: codesyntaxhighlighter 모듈 에러 해결
- codesyntaxhighlighter에서 전체 언어 highlighting이 가능하도록 해결하였습니다.

fix: codesyntaxhighlighter 모듈 에러 해결

---

src/components/form/LoginForm.tsx
src/components/layout/header/Header.tsx
src/components/layout/header/UserArea.tsx
src/components/shared/Modal.tsx
src/constants/token.ts
src/hooks/useEmailMutation.tsx
src/hooks/useNicknameMutation.tsx
src/interfaces/dto/auth/login.dto.ts
src/interfaces/dto/auth/logout.dto.ts
src/middleware.ts
src/mocks/handler/auth.ts
src/page/askQuestion/components/AskQuestionForm.tsx
src/recoil/atoms/user.tsx
src/service/auth.ts
src/service/axios.ts
src/util/actions/cookie.ts
src/util/actions/form.ts

close [#34](https://github.com/KernelSquare/Frontend/issues/34)
> 로그인 로직 수정
- 로그인 로직 변경에 따른 api 로직 및 관련 타입  수정
- 로그인 응답에 있는 유저 페이로드와 토큰을 프론트에서 쿠키로 설정하여 활용 (토큰 쿠키는 httpOnly 적용)
- 가로 모드일 때 모달의 높이가 overflow되는 현상을 발견하여 최대 높이와 overflow-y-auto를 적용하고, 모달 header에 sticky를 설정하여 모달 스크롤을 내릴때 포지션을 유지할 수 있도록 수정함
- 로그인 폼과 중복체크에서 에러 발생 시 토스트 형식으로 메시지를 보여주도록 수정함

fix: 로그인 로직 변경

---

src/app/profile/page.tsx
src/components/layout/navigation/SideNavigation.tsx
src/constants/navigationRoute.tsx
src/mocks/db/answers.ts
src/mocks/db/questions.ts
src/page/profile/MyPage.tsx
src/page/qna-detail/QnADetail.tsx
src/page/qna-detail/components/Answers/OneAnswer.tsx
src/page/qna-detail/components/MyAnswer.tsx

close: [#32](https://github.com/KernelSquare/Frontend/issues/32)
> useUser 관련 로직을 useClientSession으로 수정
- 기존에 `useUser` 유틸 함수를 통해 구현되었던 부분을 @Ryan-TheLion 님께서 구현하신 `useClientSession`을 사용하도록 로직을 수정하였습니다.

refactor: useUser 관련 로직 useClientSession으로 수정

---

src/assets/images/basic.ts
src/constants/response/member.ts
src/interfaces/dto/member/update-member-introduction.dto.ts
src/interfaces/dto/member/update-member-profile-image-dto.ts
src/mocks/handler/member.ts
src/page/user-profile/components/UserProfileMenu.tsx
src/page/user-profile/components/UserProfilePresenter.tsx
src/page/user-profile/components/introduction/Introduction.tsx
src/page/user-profile/components/profileImage/ProfileImage.tsx
src/page/user-profile/hooks/useIntroduction.tsx
src/page/user-profile/hooks/useProfileImage.tsx
src/react-query/member.ts
src/service/member.ts
src/service/route-map.ts

close: [#54 ](https://github.com/KernelSquare/Frontend/issues/54)
> 마이페이지 수정 기능을 변경된 API에 맞춰 리팩토링 하였습니다.
- 기존에 하나의 API를 사용하던 마이페이지 수정 기능을 자기소개 수정 / 프로필 이미지 수정 API로 분리하여 요청하도록 타입 및 msw 로직 등을 변경하였습니다.

feat: 프로필 정보 수정 관련 API 변동 사항 반영

---

src/page/qna-detail/components/Markdown/MdEditor.tsx
src/page/qna-detail/hooks/useToastUiEditorImageUploadHook.tsx

close: [#75](https://github.com/KernelSquare/Frontend/issues/75)
> 답변 에디터에서 공용 이미지 업로드 훅 함수 사용 시 이미지 중복 제출이 막아지지 않는 현상을 해결하였습니다.
- 기존 훅 함수가 question 관련 atomFamily에 의존하고 있어 답변 관련 페이지의 에디터에서 동일한 훅 함수 사용 시 이미지가 여러 장 업로드 되어도 에러가 발생하지 않는 문제가 발생하였습니다.
- 이를 해결하기 위해 answer 데이터를 기반으로 한 atomFamily에 의존하는 별도의 훅 함수를 만들었습니다.
- 다만, 기존 코드에서 의존하는 atomFamily만 달라진 것이어서 추후 논의 후 두 훅 함수 중 중복되는 부분은 하나로 합쳐서 분리해도 좋을 것 같아 보입니다.

fix: 답변 에디터에서 이미지 중복 제출 오류 해결

---

src/mocks/db/coffee-chat.ts
src/page/coffee-chat/detail/CoffeeChatDetailContent.tsx
src/page/qna-detail/components/Markdown/MdViewer.tsx
src/page/user-profile/components/introduction/MdViewer.tsx
src/util/editor.ts

close: [#101 ](https://github.com/KernelSquare/Frontend/issues/101)
> 기존 Toast UI Viewer에서 링크 삽입 시 상대경로로 연결되던 것을 절대경로로 연결되도록 수정하였습니다.

fix: 마크다운 Viewer 절대경로로 수정 

---

src/page/coffee-chat/detail/EnterCoffeeChat.tsx

close: [#117](https://github.com/KernelSquare/Frontend/issues/117)
> 입장하기 비활성화
- 매칭되는 룸아이디가 없을 경우 입장하기 버튼 비활성화

fix: 입장하기 비활성화

---

src/constants/limitation.ts
src/constants/message.ts
src/constants/response/answer.ts
src/constants/response/image.ts
src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
src/page/coffee-chat/create/components/HashTagsSection.tsx
src/page/coffee-chat/create/components/TimeOptions.tsx
src/page/coffee-chat/detail/reservation/mentee/TimeOptions.tsx
src/page/qna-detail/components/Answers/AnswerContentBox.tsx
src/page/qna-detail/components/Answers/AnswerList.tsx
src/page/qna-detail/components/Answers/OneAnswer.tsx
src/page/qna-detail/components/Answers/VoteBox.tsx
src/page/qna-detail/components/Markdown/MdEditor.tsx
src/page/qna-detail/components/MyAnswer.tsx
src/page/qna-detail/components/Question/HandleQuestionBox.tsx
src/page/qna-detail/components/Question/Question.tsx
src/page/qna-detail/hooks/useAnswerVote.tsx
src/page/qna-detail/hooks/useHandleMyAnswer.tsx
src/page/qna-detail/hooks/useHandleQuestion.tsx
src/page/qna-detail/hooks/useQnADetail.tsx
src/page/user-profile/components/UserProfilePresenter.tsx
src/page/user-profile/components/introduction/MdViewer.tsx
src/page/user-profile/components/profileImage/ProfileImage.tsx
src/page/user-profile/hooks/useIntroduction.tsx
src/page/user-profile/hooks/useProfileImage.tsx

close: [#169 ](https://github.com/KernelSquare/Frontend/issues/169)
> API 수정 사항 및 데이터 제한 정책을 반영하였습니다.
- 답변 상세 등 응답 코드 수정된 부분 반영하였습니다.
- 마이페이지 및 커피챗 게시글 생성 페이지 글자수 상항 제한 정책을 반영하여 미만/초과 시 제출 불가능하도록 유효성 검사 로직을 추가하였습니다.
- 마이페이지 프로필 이미지 확장자 및 규격 제한 정책을 반영하여 3MB를 초과하거나 유효하지 않은 확장자의 파일을 제출할 경우 반영되지 않도록 수정하였습니다.
- 프로필 이미지 초기화 시 이미지 저장소에서 해당 파일이 삭제되지 않던 오류를 수정하였습니다.
- react-toastify를 사용한 알림이 중복 렌더링 되는 것을 방지하기 위해 기존에 toast 객체를 사용한 부분에 `toastId` 속성을 추가해주었습니다.

refactor: API 수정 사항 및 데이터 제한 정책 반영

---

src/constants/limitation.ts
src/constants/message.ts
src/hooks/useToastUiEditorImageUploadHook.tsx
src/page/askQuestion/components/AskQuestionForm.tsx
src/page/qna-detail/components/Markdown/MdEditor.tsx
src/page/qna-detail/hooks/useToastUiEditorImageUploadHook.tsx
src/page/user-profile/hooks/useProfileImage.tsx

close: [#165](https://github.com/KernelSquare/Frontend/issues/165)
> 질문과 관련된 제한(유효성)을 적용
- 기존 Limitation 을 활용하는 방향으로 로직 적용
- 업로드 이미지 최대 개수도 Limitation에 포함할지는 서로 논의해서 수정해야 될 것 같아 해당 이슈에서는 적용하지 않음

fix: 질문 작성 및 수정 제한 적용

---

src/app/page.tsx
src/components/icons/Icons.tsx
src/components/shared/Inner.tsx
src/constants/layoutMeta.ts
src/mocks/handler/search.ts
src/page/landing/Landing.tsx
src/page/landing/components/LandingHeader.tsx
src/page/landing/components/LandingSearchBar.tsx
src/page/search/Search.tsx
tailwind.config.ts

[#180 ](https://github.com/KernelSquare/Frontend/issues/180)
> 랜딩 페이지 메인이 되는 화면을 구현하였습니다. 
[홈 - 커널스퀘어 - Chrome 2024-02-29 00-45-00.webm](https://github.com/KernelSquare/Frontend/assets/123251211/c4a892e1-0a91-41ee-a09d-989e66f28bb5)
- 메인 화면 UI를 퍼블리싱 했습니다.
- 헤더의 각 요소들은 해당하는 페이지로 라우팅되며 SearchBar에 검색 시 검색 결과 페이지로 이동합니다.
- 추가로 검색 페이지의 필터 기능들을 주석 처리해두었습니다. (구현 전에 임시로 만들어 둔 부분인데 원하는 리액션이 발생하지 않는 버튼이 많다는 피드백을 반영하여 우선 숨김 처리하였습니다.)
- MSW 검색 로직을 일부 수정하였습니다. (모두 `toLowerCase( )`를 적용하여 단어만 일치하면 검색되도록 수정)

feat: 랜딩 페이지 메인 화면 구현 

---

src/page/coding-meetings/create/components/CustomMap/kakaoMap.tsx

> 모각코 생성 시 지도 좌표 정보 수정
- 지도 좌표 정보가 반대로 들어가는 것을 수정하였습니다.

fix: 지도 정보 수정

---

src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
src/page/coding-meetings/create/components/LocationSection.tsx

> 모각코 게시글 수정 후 상세 페이지로의 이동 시 새로고침 없이도 데이터가 반영될 수 있도록 라우터 캐시를 초기화하였습니다.

fix: 수정 시 데이터 반영 지연 문제 해결 

---

package.json
pnpm-lock.yaml
src/app/coding-meetings/[token]/page.tsx
src/components/shared/page-template/ListPage.tsx
src/components/ui/PopOver.tsx
src/page/coding-meetings/detail/Comments.tsx
src/page/coding-meetings/detail/DetailPage.tsx
src/page/coding-meetings/detail/Map.tsx
src/page/coding-meetings/detail/UserInfo.tsx
src/page/coding-meetings/detail/kakao-map/Control.tsx
src/page/coding-meetings/detail/kakao-map/KakaoMapError.tsx
src/page/coding-meetings/detail/kakao-map/Map.tsx
src/page/coding-meetings/detail/kakao-map/MapContainer.tsx
src/page/coding-meetings/main/ScrollTopButton.tsx

close: [#207](https://github.com/KernelSquare/Frontend/issues/207)
> 모각코 상세 QA 반영
- 상단 타이틀에 모각코 툴팁 생성
- 로그인 하지 않은 유저가 유저 영역 hover시 커서가 포인터로 변경되지 않도록 수정
- 지도 컴포넌트 height 수정
- 기본 지도 스크롤 이벤트의 줌인/줌아웃 이벤트를 비활성화 시키고, 사용자가 원할 경우 직접 확대 축소 버튼을 눌러서 볼 수 있도록 수정
-  페이지를 스크롤 할 때 원치 않는 지도 확대 축소 는 사용자 경험에 안 좋을 것이라 생각 되어 수정
-  수정 이후 기존 스크롤 이벤트를 원하는 것으로 피드백이 올 경우 기존 이벤트를 허용하는 것으로 수정하여 다시 반영할 예정
- 카카오 맵 로드, 실패 렌더링 / 해당 에러 발생시 Sentry에 에러 전송
- 서버 시간 -> 한국 시간(클라이언트 기준) 시간 컴포넌트 클라이언트 환경에서 렌더링되기 이전까지의 로딩 렌더링 추가
- 댓글 작성 이후 댓글 입력 초기화
- 화면 최상단으로 이동 할 수 있는 scrollTop 버튼 추가

fix: 모각코 상세, 메인

---

src/components/shared/auth-modal/MyPageGuardModal.tsx
src/components/shared/auth-modal/UserProfileGuardModal.tsx
src/constants/timeOptions.ts
src/page/coding-meetings/create/CreateCodingMeetingPage.tsx
src/page/coding-meetings/create/hooks/useHandleCreateCodingMeetingTime.tsx
src/page/coffee-chat/create/CreateCoffeeChatReservationPage.tsx
src/page/coffee-chat/create/CreateCoffeeChatReservationPage.types.ts
src/page/coffee-chat/create/components/HashTagsSection.tsx
src/page/coffee-chat/create/components/MdEditor.tsx
src/page/coffee-chat/create/components/ScheduleSection.tsx
src/page/coffee-chat/create/components/TimeOptions.tsx
src/page/coffee-chat/detail/CoffeeChatDetailPage.tsx
src/page/qna-detail/components/Answers/AnswerContentBox.tsx
src/page/user-profile/components/introduction/Introduction.tsx
src/page/user-profile/components/introduction/MdEditor.tsx

[#214 ](https://github.com/KernelSquare/Frontend/issues/214)
> 금일 작성된 검수 피드백 사항을 반영하여 수정하였습니다.
- 마이페이지 자기소개글 글자 수 카운터 컴포넌트 추가 및 disabled 처리
- 로그인하지 않고 접속할 경우 노출되는 접근 제한 모달의 '홈 버튼' 클릭 시 랜딩 페이지가 아닌 로그인 버튼이 보이는 qna 목록 페이지로 이동하도록 설정
- 커피챗 생성 시 본문 내용 카운터 컴포넌트 추가 및 disabled 처리 
- 예약하지 않은 커피챗 상세 페이지에서는 커피챗 입장 버튼 노출 막기
- 커피챗 등록글 생성하기 time의 값이 유지되는 오류 수정
- time picker에서 시간 한 자리 수일 경우 앞에 '0' 붙이기

fix: 검수 피드백 반영

---

src/components/shared/pagination/Pagination.tsx
src/components/shared/qna/QnAList.tsx
src/page/coffee-chat/main/CoffeeChatListContainer.tsx

[#213](https://github.com/KernelSquare/Frontend/issues/213)
> 수정된 페이지네이션 적용
- 커피챗 리스트, 검색 페이지에서도 수정된 페이지네이션이 적용될 수 있도록 수정
- 페이지네이션 label prop 제거
- 검색 페이지 리스트에도 다른 리스트 페이지에서와 동일한 gap을 유지하도록 수정

fix: 커피챗, search 페이지네이션 수정

---

src/page/qna/components/QnAList.tsx

close: [#239](https://github.com/KernelSquare/Frontend/issues/239)
- 멤버id로 매핑될 수 있도록 수정

fix: QnA리스트 멤버id

---

src/components/form/LoginForm.tsx

[#288](https://github.com/KernelSquare/Frontend/issues/288)
> 로그인 버튼 수정
- 로그인 버튼을 disabled 하지는 않고, 관련 토스트 메시지를 보여주는 것으로 수정

fix: 로그인 버튼

---

src/app/question/[id]/page.tsx

[#307](https://github.com/KernelSquare/Frontend/issues/307)
> 질문 og, twitter 수정
- 질문 이미지가 있으면 해당 이미지, 없을 경우 기본 이미지가
og, twitter에 반영 되도록 수정

fix: 질문이미지를 og, twitter 에 반영

---

src/app/oauth/github/page.tsx
src/page/oauth/github/error/OAuthGithubError.tsx
src/page/oauth/github/error/OAuthGithubErrorWrapper.tsx

[#306](https://github.com/KernelSquare/Frontend/issues/306)
> 깃허브 소셜 로그인 에러 페이지 수정
- Github Login Error -> Github Login Fail 로 제목 수정
- errorCode 로 분류하여 에러 메시지를 보여주도록 수정

fix: 깃허브 로그인 에러 페이지 수정

---

src/page/coding-meetings/util/cm-token.ts

- 백엔드 모각코 토큰이 cm_이후 소문자나 숫자로도 시작하는 경우가 있는 것 같아 cm- 로 시작하는 것으로 수정
- 메타데이터 생성시 실패하지 않고 데이터를 가져온 이후 og가 표시가 되지 않는 이유는 좀 더 확인해봐야 될 것 같음 (fallback 상황에서는 og 표시되지만, 없는 페이지라 의미가 없음)

[fix] 모각코 상세 url

---

src/components/layout/header/alerm/Alerm.tsx
src/mocks/handler/index.ts
src/mocks/handler/notification/get-alerts.ts
src/mocks/handler/notification/index.ts

[#329](https://github.com/KernelSquare/Frontend/issues/329)
> 알람 배지 스타일 수정, 말줄임표가 적용되도록 css 수정
- 알림 목록 api에 대해 간단한 msw 핸들러 적용
- 알람 배지 스타일 수정, 말줄임표가 적용되도록 css 수정
- 답변랭크, 커피챗 요청 강조 색상 css 수정

알람 배지 수정, 말줄임표 적용

---

src/components/layout/header/alerm/Alerm.tsx
src/mocks/handler/index.ts
src/mocks/handler/notification/get-alerts.ts
src/mocks/handler/notification/index.ts

[#329](https://github.com/KernelSquare/Frontend/issues/329)
> 알람 배지 스타일 수정, 말줄임표가 적용되도록 css 수정
- 알림 목록 api에 대해 간단한 msw 핸들러 적용
- 알람 배지 스타일 수정, 말줄임표가 적용되도록 css 수정
- 답변랭크, 커피챗 요청 강조 색상 css 수정

알림 리스트 스타일 수정, msw

---

src/constants/limitation.ts
src/constants/message/validation.ts
src/page/coffee-chat/create/components/sections/content/ContentSection.tsx
src/page/coffee-chat/create/controls/rules/chat-content-rules.ts
src/styles/react-calendar/Base.css
src/styles/react-calendar/CoffeeChatTile.css

#342
> 소개글 유효성 검사 수정, react 캘린더 타일 css 수정
- 소개글이 1000자 이상일 경우 에러 응답 확인되어 수정 함 (10자이상 1000자 이하)
- 휴대폰에서 UX를 개선하기 위해 커피챗 상세 페이지의 캘린더 css 개선
- focus 된 타일 배경과 active상태의 타일 배경을 일치시킴

커피챗 소개글 유효성 검사 수정, 커피챗 상세 캘린더 css개선

---

public/firebase-messaging-sw.js
src/app/api/send-fcm/route.ts
src/interfaces/push/push-action.ts
src/interfaces/push/push-notification.ts
src/interfaces/push/push-type.ts
tsconfig.json

#367
> 액션버튼(글보기) 클릭시 새 창 열리지 않는 문제 개선, 타입 리팩토링
- api에서 link 주소를 전달하고 알림 클릭 이벤트에서 해당 주소를 활용하도록 수정
- firebase-messaging-sw 서비스워커에서 기본 제공해주는 WebWorker 관련 타입을 사용할 수 있도록 타입 관련 작업
- tsconfig.json : lib에 WebWoker 추가
- interface/push : 서비스워커에서 사용할 푸시 알림 관련 타입 추가
- firebase-messaging-sw.js: jsdoc import 로 관련 타입 활용 및 상단에 reference lib WebWorker 적용하여 기본 타입 적용될 수 있도록 함

fix: 액션 버튼 클릭시 창 열리지 않음

---

public/firebase-messaging-sw.js
src/app/api/send-fcm/route.ts
src/interfaces/dto/fcm/send-fcm.dto.ts
src/interfaces/push/push-action.ts
src/interfaces/push/push-notification.ts
src/interfaces/push/push-type.ts
src/page/qna-detail/components/Answers/form/CreateAnswerForm.tsx

#367
> 답변 푸시 알림 아이콘 수정, actions 제거
- 답변 알림 시 유저 프로필 이미지가 있을 경우 프로필 이미지 주소를 아이콘으로 설정
- 알림 actions 제거, actions 관련 타입 제거
- 모바일 백그라운드 상태에서 알림 표시는 되지만, 클릭시 clients.openWindow 가 되지 않음
- 데스크탑에서는 잘되지만, 모바일에서 액션 버튼(문구)가 노출은 되지만 실제 클릭시 모든 경우에 대응할 수 없음 
=> 일관된 경험을 제공하기 위해 actions는 적용하지 않음

fix: 알림 아이콘 수정, 액션 제거
